################################################################################
heat_temp:
  name: Consigne
  icon: mdi:home-thermometer-outline
################################################################################
notification_1:
  max: 255
notification_2:
  max: 255
notification_3:
  max: 255
notification_4:
  max: 255
notification_5:
  max: 255
notification_6:
  max: 255
notification_7:
  max: 255
notification_8:
  max: 255
notification_9:
  max: 255
notification_10:
  max: 255
################################################################################
motivation_1:
  max: 255
motivation_2:
  max: 255
motivation_3:
  max: 255
motivation_4:
  max: 255
################################################################################
json_activities:
  max: 255
json_exterior_average_temp:
  max: 255
################################################################################
security_alarm:
  max: 255