################################################################################
min_distance_from_home:
  min: 0
  max: 20040000
################################################################################
water_heat_pct:
  icon: mdi:water-boiler
  name: Pourcentage en heures creuses
  min: 0
  max: 100
  unit_of_measurement: '%'
water_heat_duration:
  icon: mdi:av-timer
  name: Temps d'activation manuel
  min: 0
  max: 360
  unit_of_measurement: 'min'
water_heat_person_number:
    min: 1
    max: 8
water_heat_adjustment:
    min: -10
    max: 10
################################################################################
sun_light_angle_setting_rising:
  min: 1
  max: 12
  name: Angle couché / levé du soleil
  icon: mdi:theme-light-dark
  unit_of_measurement: '°'    
sun_light_angle_dusk_dawn:
  min: -5
  max: 0
  name: Angle crépuscule / aube
  icon: mdi:theme-light-dark
  unit_of_measurement: '°'
elevation:
  min: -100
  max: 100
  unit_of_measurement: '°'
color_rotate:
  name: Couleur lorsque la lumière s'éteint
  icon: mdi:palette
  min: 0
  max: 360
  unit_of_measurement: '°'
color_segment:
  name: Angle de balayage chromatique
  icon: mdi:palette
  min: 0
  max: 360
  unit_of_measurement: '°'
low_light_compensation:
  name: Compensation faible luminosité
  icon: mdi:cloud-off-outline
  min: 50
  max: 1000
  unit_of_measurement: 'Lux'
illuminance_light:
  name: Luminosité extérieure
  icon: mdi:theme-light-dark
  min: 0
  max: 100000
  unit_of_measurement: 'Lux'
################################################################################
sun_angle_cover_on:
  name: Angle du soleil ouverture volets
  icon: mdi:weather-sunset-up
  min: -15
  max: 15
  unit_of_measurement: '°'
sun_angle_cover_off:
  name: Angle du soleil fermeture volets
  icon: mdi:weather-sunset-up
  min: -15
  max: 15
  unit_of_measurement: '°'
################################################################################
temp_min:
  name: Température basse d'alerte
  icon: mdi:home-thermometer-outline
  min: 18
  max: 22
  unit_of_measurement: '°C'
temp_max:
  name: Température haute d'alerte
  icon: mdi:home-thermometer-outline
  min: 22
  max: 26
  unit_of_measurement: '°C'
humidity_min:
  name: Humidité basse d'alerte
  icon: mdi:water-percent
  min: 0
  max: 100
  unit_of_measurement: '%'
humidity_max:
  name: Humidité haute d'alerte
  icon: mdi:water-percent
  min: 0
  max: 100
  unit_of_measurement: '%'
################################################################################
low_battery_level:
  name: Niveau d'alerte batterie faible
  icon: mdi:battery-alert-variant-outline
  min: 5
  max: 30
  step: 1
  unit_of_measurement: '%'
################################################################################
speaker_day_mode_volume:
  name: Volume en mode jour
  icon: mdi:volume-high
  min: 0
  max: 100
  step: 1
  unit_of_measurement: '%'
speaker_night_mode_volume:
  name: Volume en mode nuit
  icon: mdi:volume-medium
  min: 0
  max: 100
  step: 1
  unit_of_measurement: '%'